Graphics work (WIP)
pettett/ch-concentrated-solar pull request #4
Opened 2024-12-27 01:02 UTC by snouz

-Fixed some shadow positions
-Fixed turret tower displaying behind object on ground

2025-01-19 19:01 UTC, pettett requested changes
The colour grading especially is really good on these. Something I need to work on for sure.

2025-01-19 19:01 UTC, pettett commented on thumbnail.png
Is it possible to get this new image with the same transparent BG?

2025-01-19 19:01 UTC, pettett commented on graphics/solar-power-tower-shadow.png
The end of the blur is a sharp edge in game, and I'm not sure if I think the blur fits with in game entities, even though it technically makes sense. e.g. large power pole does not even start to blur.

2025-03-02 15:26 UTC, snouz commented
Sorry for the delay, I got distracted with another project, then had a kid : )

I got to the changes you wanted, and optimized the png files with spritter

2025-03-02 18:18 UTC, pettett commented
Thanks, no problems, and congratulations!

2025-03-02 18:18 UTC, merged